name: icar
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  another_flushbar: ^1.12.30
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.0
  csc_picker: ^0.2.7
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  easy_localization: ^3.0.7
  equatable: ^2.0.5
  figma_squircle: ^0.5.3
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.14
  get_it: ^8.0.2
  go_router: ^14.6.0
  google_sign_in: ^6.2.2
  iconsax: ^0.0.8
  intl: ^0.19.0
  introduction_screen: ^3.1.14
  json_annotation: ^4.9.0
  json_serializable: ^6.7.1
  lottie: ^3.1.3
  permission_handler: ^11.3.1
  phone_form_field: ^10.0.1
  pin_code_fields: ^8.0.1
  pretty_dio_logger: ^1.4.0
  rename: ^3.0.2
  shared_preferences: ^2.3.3
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0

dependency_overrides:
  build_runner: ^2.4.7

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lang/
    - assets/images/
    - assets/icons/
  fonts:
    - family: Neo
      fonts:
        - asset: assets/fonts/neo/Neo-Regular.otf
        - asset: assets/fonts/neo/Neo-Medium.otf
          weight: 500
        - asset: assets/fonts/neo/Neo-Bold.otf
          weight: 700
        - asset: assets/fonts/neo/Neo-Italic.otf
          style: italic
        - asset: assets/fonts/neo/Neo Sans Std Medium Italic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/neo/Neo Sans Std Bold Italic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/neo/Neo-Black-Italic.otf
          weight: 900
          style: italic
        - asset: assets/fonts/neo/Neo Sans Std Ultra.otf
          weight: 800
    - family: IBM
      fonts:
        - asset: assets/fonts/ibm/IBM-Regular.ttf
        - asset: assets/fonts/ibm/IBM-Medium.ttf
          weight: 500
        - asset: assets/fonts/ibm/IBM-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ibm/IBM-Bold.ttf
          weight: 700
    - family: AvenirNextLTPro
      fonts:
        - asset: assets/fonts/avenir/AvenirNextLTPro-Regular.otf
        - asset: assets/fonts/avenir/AvenirNextLTPro-Bold.otf
        - asset: assets/fonts/avenir/AvenirNextLTPro-BoldCn.otf
          weight: 700
        - asset: assets/fonts/avenir/AvenirNextLTPro-Demi.otf
          weight: 600
        - asset: assets/fonts/avenir/AvenirNextLTPro-It.otf
          style: italic
