
// import 'package:icar/core/localization/local_keys.dart';

// class AppLocalization extends Translations {
//   @override
//   Map<String, Map<String, String>> get keys =>
//       {'en': englishStrings, 'ar': arabicStrings};
// }
// const arabicStrings = {
  
//   Lkeys.w: 'أ',
//   Lkeys.d: 'ي',

//   Lkeys.pm: 'م',
//   Lkeys.am: 'ص',

//   Lkeys.participants: 'المشاركين',
//   Lkeys.pressBackAgainToExit : 'اضغط مرة أخرى للخروج',
//   Lkeys.multimedia: 'الوسائط',
//   Lkeys.mentions: 'المنشن',
//   Lkeys.description: 'الوصف',
//   Lkeys.openToJoin: 'مفتوح للانضمام',
//   Lkeys.requestToJoin: 'طلب انضمام',
//   Lkeys.noParticipants: 'ما في مشاركين، كن أول من يشارك',
//   Lkeys.noComments: 'ما في تعليقات، كن أول من يعلق',
//   Lkeys.noMultimedia: 'ما في وسائط',
//   Lkeys.noDescription: 'ما في وصف',
//   Lkeys.totalCost: 'الإجمالي',
//   Lkeys.activitiyDetails: 'تفاصيل النشاط',
//   Lkeys.details: 'التفاصيل',
//   Lkeys.no: 'لا',
//   Lkeys.yes: 'نعم',
//   Lkeys.from: 'من',
//   Lkeys.to: 'إلى',
//   Lkeys.resendCode: 'إعادة إرسال الرمز',
//   Lkeys.startAt: 'يبدأ في',
//   Lkeys.endAt: 'ينتهي في',
//   Lkeys.next: 'التالي',
//   Lkeys.submit: 'إرسال',
//   Lkeys.login: 'تسجيل الدخول',
//   Lkeys.email: 'الإيميل',
//   Lkeys.signup: 'تسجيل',
//   Lkeys.logout: 'تسجيل الخروج',
//   Lkeys.success: 'تم بنجاح',
//   Lkeys.addPhotoOrAvatar: 'أضف صورة أو صورة رمزية',
//   Lkeys.accountData: 'بيانات الحساب',
//   Lkeys.enterAccountDataToContinue: 'ادخل بيانات حسابك عشان تكمل',

//   Lkeys.fullName: 'الاسم الكامل',
//   Lkeys.nickname: 'الاسم المستعار',
//   Lkeys.gender: 'الجنس',
//   Lkeys.male: 'ذكر',
//   Lkeys.female: 'أنثى',
//   Lkeys.birthDate: 'تاريخ الميلاد',

//   Lkeys.discard: 'تجاهل',
//   Lkeys.discardChanges: 'تجاهل التغييرات',
//   Lkeys.discardChangesDesc: 'هل تريد تجاهل التغييرات؟',

//   Lkeys.save: 'حفظ',
//   Lkeys.saved: 'تم الحفظ',
//   Lkeys.chooseGender: 'اختر الجنس',
//   Lkeys.phoneRequired: 'رقم الجوال مطلوب',
//   Lkeys.phoneTooShort: 'رقم الجوال قصير مره',
//   Lkeys.phoneTooLong: 'رقم الجوال طويل مره',
//   Lkeys.phoneNoStart0: 'رقم الجوال ما يبدأ بصفر',
//   Lkeys.phoneShouldStart5: 'رقم الجوال لازم يبدأ بـ 5',
//   Lkeys.phoneInvalid: 'ادخل رقم جوال صحيح',
//   Lkeys.phoneNumber: 'رقم الجوال',
//   Lkeys.phoneNumberHint: 'ادخل رقم جوالك',
//   Lkeys.continueText: 'استمر',
//   Lkeys.password: 'كلمة المرور',
//   Lkeys.confirmPassword: 'تأكيد كلمة المرور',
//   Lkeys.getStarted: 'ابدأ',

//   Lkeys.forgetPassword: 'نسيت كلمة المرور؟',

//   Lkeys.signInWithGoogle: 'سجل دخولك بجوجل',
//   Lkeys.notVerified: 'لسه ما تم التحقق',
//   Lkeys.loading: 'جاري التحميل...',
//   Lkeys.successVerifyYourEmail: 'تم التحقق من إيميلك بنجاح',
//   Lkeys.nothingFound: 'ما في شيء هنا',
//   Lkeys.tryAgain: 'حاول مرة ثانية',
//   Lkeys.thereIsSomethingError: 'في خطأ، حاول لاحقًا',
//   Lkeys.emailCannotEmpty: 'الإيميل ما يكون فاضي',
//   Lkeys.invalidEmailFormat: 'صيغة الإيميل غير صحيحة',
//   Lkeys.shortPasswordError: 'كلمة المرور لازم تكون أكثر من 8 حروف',
//   Lkeys.longPasswordError: 'كلمة المرور طويلة جدًا',
//   Lkeys.passwordsDoesNotMatch: 'كلمة المرور غير متطابقة',
//   Lkeys.noRecordFound: 'ما في سجلات',
//   Lkeys.requiredField: 'حقل مطلوب',
//   Lkeys.nameCannotEmpty: 'الاسم ما يكون فاضي',
//   Lkeys.phoneCannotEmpty: 'رقم الجوال ما يكون فاضي',
//   Lkeys.emailNotFound: 'هذا الإيميل مو موجود',
//   Lkeys.otpTitle: 'كود التحقق',
//   Lkeys.otpSubTitle: 'تحقق',
//   Lkeys.otpMessage: 'ادخل رمز التحقق المرسل إلى',
//   Lkeys.alert: 'تنبيه',
//   Lkeys.ohSnap: 'يا ساتر',

//   Lkeys.addActivity: 'أضف نشاط',
//   Lkeys.addEvent: 'أضف حدث او فعالية',
//   Lkeys.addReel: 'أضف ريل',
//   Lkeys.addPost: 'أضف منشور', 
//   Lkeys.addStory: 'أضف قصة',
//   Lkeys.currentActivity: 'الحالية',
//   Lkeys.all: 'الكل',
//   Lkeys.previousActivity: 'السابقة',
//   Lkeys.activity: 'النشاط',
//   Lkeys.activities: 'الأنشطة',
//   Lkeys.reels: 'ريلز',
//   Lkeys.noReelsFound: 'ما في ريلز',
//   Lkeys.sendMessage: 'مراسلة',

//   Lkeys.uploadImage: 'رفع صورة',
//   Lkeys.uploadImages: 'رفع صور',
//   Lkeys.noActivityfoundInYourAccount: 'ما في نشاطات بحسابك، أضف نشاط',
//   Lkeys.noActivityfoundInThisAccount: 'ما في نشاطات في هذا الحساب',
//   Lkeys.whenPeopleTagYouInActivity: 'لما يذكرك الناس في نشاط، بتشوفه هنا',
//   Lkeys.map: 'الخريطة',
//   Lkeys.events: 'الأحداث والفعاليات',
//   Lkeys.users : 'المستخدمين',
//   Lkeys.viewDetails: 'عرض التفاصيل',

//   Lkeys.emailSent: 'تم إرسال الإيميل بنجاح!',
//   Lkeys.congratulations: 'مبروك',
//   Lkeys.emailLinkToResetPassword: 'رابط لإعادة تعيين كلمة المرور',
//   Lkeys.accountCreateVerifyEmail: 'إنشاء حساب تحقق من الإيميل',
//   Lkeys.welcomeBack: 'أهلًا بعودتك',
//   Lkeys.loginSubTitle: 'ادخل رقم جوالك وانضم لعالم مليء بالأنشطة',
//   Lkeys.loginTitle: 'تسجيل الدخول',
//   Lkeys.rememberMe: 'تذكرني',
//   Lkeys.dontHaveAnAccount: 'ما عندك حساب',
//   Lkeys.enterYour: 'ادخل',
//   Lkeys.resetPassword: 'إعادة تعيين كلمة المرور',
//   Lkeys.or: 'أو',
//   Lkeys.connectWith: 'الاتصال بـ',
//   Lkeys.facebook: 'فيسبوك',
//   Lkeys.google: 'جوجل',
//   Lkeys.signUpTitle: 'ابدأ!',
//   Lkeys.signUpSubTitle: 'أنشئ ملفك الشخصي وابدأ رحلتك.',
//   Lkeys.alreadyHaveAnAccount: 'عندك حساب؟',
//   Lkeys.forgetPasswordTitle: 'اختر!',
//   Lkeys.forgetPasswordSubTitle: 'ادخل إيميلك لإعادة تعيين كلمة المرور.',
//   Lkeys.resetViaEMail: 'إعادة تعيين عبر الإيميل',
//   Lkeys.resetViaPhone: 'إعادة تعيين عبر الجوال',
//   Lkeys.forgetPhoneSubTitle: 'ادخل رقم جوالك المسجل لاستلام كود التحقق',
//   Lkeys.forgetMailSubTitle: 'ادخل إيميلك المسجل لاستلام كود التحقق',
//   Lkeys.emailVerificationTitle: 'تحقق من إيميلك',
//   Lkeys.emailVerificationSubTitle: 'أرسلنا لك رابط تحقق على إيميلك. تفقد الإيميل وانقر على الرابط للتحقق. \n\n إذا لم يتم توجيهك تلقائيًا بعد التحقق، انقر على زر المتابعة.',
//   Lkeys.resendEmailLink: 'إعادة إرسال رابط الإيميل',
//   Lkeys.backToLogin: 'العودة لتسجيل الدخول',
//   Lkeys.backToProfile: 'العودة للملف الشخصي',
//   Lkeys.profile: 'الملف الشخصي',
//   Lkeys.editProfile: 'تعديل الملف الشخصي',
//   Lkeys.logoutDialogHeading: 'تسجيل الخروج',
//   Lkeys.profileHeading: 'محمد السايراني',
//   Lkeys.profileSubHeading: 'Mo7hammedalsayani@gmail.com',
//   Lkeys.menuLogout: 'تسجيل الخروج',
//   Lkeys.menuSettings: 'الإعدادات',
//   Lkeys.menuInformation: 'معلومات',
//   Lkeys.menuBillingDetails: 'تفاصيل الفاتورة',
//   Lkeys.menuUserManagement: 'إدارة المستخدمين',
//   Lkeys.delete: 'حذف',
//   Lkeys.joined: 'انضم',
//   Lkeys.joinedAt: '31 مايو 2024',

//   Lkeys.invalidNameFormat: 'صيغة الاسم غير صحيحة',
//   Lkeys.invalidFormat: 'الصيغة غير صحيحة',
//   Lkeys.shortUsernameError: 'اسم المستخدم لازم يكون أطول من 3 حروف',
//   Lkeys.longUsernameError: 'اسم المستخدم لازم يكون أقصر من 10 حروف',
//   Lkeys.invalidUsernameFormat: 'صيغة اسم المستخدم غير صحيحة، لازم يبدأ بـ @',

//   Lkeys.textChatDedicated: 'دردشة نصية مخصصة',
//   Lkeys.socialMedia: 'وسائل التواصل الاجتماعي',
//   Lkeys.chatRoom: 'غرف الدردشة',
//   Lkeys.chatRoomDesc: 'أنشئ غرفة، أضف اهتماماتك، وسولف مع الناس.',
//   Lkeys.randomRoom: 'محادثات عشوائية',
//   Lkeys.randomRoomDesc: 'ابحث عن صديق عشوائي حسب اهتماماتك، وارسل طلب دردشة',
//   Lkeys.craftYourProfile: 'عدل ملفك الشخصي',
//   Lkeys.craftYourProfileDesc: 'ابحث عن صديق عشوائي حسب اهتماماتك، وارسل طلب دردشة',
//   Lkeys.createChatPost: 'أضف منشور نصي',
//   Lkeys.createChatPostDesc: 'اكتب أفكارك أو مشاعرك ودع الناس يتفاعلوا معها.',
//   Lkeys.letsStart: 'لنبدأ',
//   Lkeys.signInTo: 'سجل دخولك إلى',
//   Lkeys.continue1: 'استمر',
//   Lkeys.signInDesc: 'اختر طريقة من الطرق أدناه وسجل دخولك لتكمل استخدام التطبيق',

//   Lkeys.signInWithEmail: 'سجل دخولك بالإيميل',
//   Lkeys.signInWithApple: 'سجل دخولك بأبل',
//   Lkeys.bySelectingAgree: 'عند تحديد "موافقة ومتابعة" أدناه،',
//   Lkeys.iAgreeTo: ' أوافق على',
//   Lkeys.termsAndConditions: 'الشروط والأحكام',
//   Lkeys.and: 'و',
//   Lkeys.privacyPolicy: 'سياسة الخصوصية',
//   Lkeys.selectYour: 'اختر',
//   Lkeys.select  : 'اختر',
//   Lkeys.interests: 'اهتماماتك',
//   Lkeys.interestsDesc: 'حدد بعض الاهتمامات، عشان نقدر نفضل غرف الدردشة لك.',
//   Lkeys.setYour: 'حدد',
//   Lkeys.username: 'اسم المستخدم',
//   Lkeys.setUsernameDesc: 'أنشئ اسم مستخدم يلفت الانتباه، وبيظهر في ملفك الشخصي',
//   Lkeys.thisUsernameIsNotAvailable: 'اسم المستخدم هذا غير متاح',
//   Lkeys.thisUsernameIsAvailable: 'اسم المستخدم متاح',
//   Lkeys.profilePicture: 'صورة الملف الشخصي',
//   Lkeys.setProfileDesc: 'جميل، الآن أخبرنا كيف تبدو.',
//   Lkeys.feed: 'المنشورات',
//   Lkeys.rooms: 'الغرف',
//   Lkeys.randoms: 'عشوائية',
//   Lkeys.chats: 'الدردشات',
//   Lkeys.chat: 'الدردشة',

//     Lkeys.exit: 'خروج',
//   Lkeys.exitAppDesc: 'هل تريد الخروج من التطبيق؟',

//   Lkeys.comments: 'التعليقات',
//   Lkeys.writeSomething: 'اكتب شيء...',
//   Lkeys.replyingTo: 'الرد على',
//   Lkeys.showReply: 'عرض الرد',
//   Lkeys.showReplies: 'عرض الردود',
//   Lkeys.hideReplies: 'إخفاء الردود',
//   Lkeys.reply: 'رد',
//   Lkeys.viewers: 'المشاهدين',
//   Lkeys.replies: 'الردود',
//   Lkeys.report: 'إبلاغ',
//   Lkeys.share: 'مشاركة',
//   Lkeys.exploreBy: 'استكشاف بواسطة',
//   Lkeys.members: 'الأعضاء',
//   Lkeys.member : 'عضو',

//   Lkeys.roomsBy: 'الغرف بواسطة',

//   Lkeys.requested: 'تم الطلب',
//   Lkeys.cancelRequest: 'إلغاء الطلب',
//   Lkeys.requestedFailed: 'فشل الطلب',
//   Lkeys.requestToJoinThisActivity: 'طلب الانضمام لهذا النشاط',
//   Lkeys.requestToJoinDesc: 'اضغط على الزر بالأسفل واطلب الانضمام. بتضاف للنشاط بعد ما يوافق المشرف على طلبك.',
//   Lkeys.joinThisActivity: 'انضم لهذا النشاط',
//   Lkeys.searching: 'يبحث',
//   Lkeys.searchingDesc: 'ابحث عن ملفات شخصية عشوائيًا بناءً على اهتماماتك، واطلب دردشة مع الغرباء.',
//   Lkeys.found: 'وجد',

//   Lkeys.viewFullProfile: 'عرض الملف الكامل',
//   Lkeys.followers: 'المتابعين',
//   Lkeys.follow: 'متابعة',
//   Lkeys.followBack: 'رد المتابعة',
  
//   Lkeys.following: 'يتابع',
//   Lkeys.unFollow: 'إلغاء المتابعة',

//   Lkeys.profileSetting: 'إعدادات الملف الشخصي',

//   Lkeys.organizer: 'المنظم',
//   Lkeys.becomeAnOrganizer: 'كن منظمًا',
//   Lkeys.anOrganizer: 'منظم',
//   Lkeys.organizerProfile: 'الملف الشخصي للمنظم',

//   Lkeys.roomsYouOwn: 'الغرف اللي تمتلكها',
//   Lkeys.roomsInvitation: 'دعوات الغرفة',
//   Lkeys.notification: 'الإشعارات',
//   Lkeys.profileVerification: 'التحقق من الملف الشخصي',
//   Lkeys.pushNotification: 'دفع الإشعارات',
//   Lkeys.pushNotificationDesc: 'استمر بتشغيله عشان تستقبل الإشعارات',
//   Lkeys.getInvitedToRooms: 'استقبال دعوات الغرف',
//   Lkeys.getInvitedToRoomsDesc: 'مسؤولي الغرف يقدرون يرسلون لك دعوة تنضم للغرف إذا خليتها شغالة',
//   Lkeys.helpSupport: 'المساعدة والدعم',
//   Lkeys.logOut: 'تسجيل خروج',
//   Lkeys.deleteMyAcc: 'احذف حسابي',
//   Lkeys.version: 'الإصدار',
//   Lkeys.createNewRoom: 'إنشاء غرفة جديدة',
//   Lkeys.selectProfileImage: 'حدد صورة الملف الشخصي',
//   Lkeys.selectBackgroundImage: 'حدد صورة الخلفية',
//   Lkeys.roomName: 'اسم الغرفة',
//   Lkeys.shortDescription: 'وصف قصير',
//   Lkeys.selectTag: 'حدد الاشارة',
//   Lkeys.tag: 'الإشارة',
//   Lkeys.tagUsers: 'إشارة للمستخدمين',
//   Lkeys.usersTagged: 'المستخدمين المشار إليهم',

//   Lkeys.tags: 'الإشارات',
//   Lkeys.cancel: 'إلغاء',
//   Lkeys.createRoom: 'إنشاء غرفة',
//   Lkeys.whatIsYourRoomAbout: 'ما هي غرفتك...',
//   Lkeys.makeRoomPublic: 'اجعل الغرفة عامة',
//   Lkeys.makeRoomPublicDesc: 'استمر بتشغيله إذا تبغى غرفتك تظهر للجميع',
//   Lkeys.joinAfterRequest: 'الانضمام بعد الطلب',
//   Lkeys.joinAfterRequestDesc: 'إذا كان هذا شغال، لازم الأعضاء الجدد يطلبون الانضمام للغرفة والمشرف يوافق عليه.',
//   Lkeys.invitedBy: 'بدعوة من',

//   Lkeys.post: 'منشور',
//   Lkeys.writeHere: 'اكتب هنا...',
//   Lkeys.block: 'حظر',
//   Lkeys.reject: 'رفض',
//   Lkeys.accept: 'قبول',
//   Lkeys.acceptInvitation: 'قبول دعوة',
//   Lkeys.requestDesc: 'يريد الدردشة معك، وافق إذا تبغى تتواصل معه',
//   Lkeys.roomInfo: 'معلومات الغرفة',
//   Lkeys.muteNotification: 'كتم الإشعارات',
//   Lkeys.deleteActivity: 'حذف النشاط',
//   Lkeys.deleteReel: 'حذف الريل',
//   Lkeys.deleteReelDesc: 'هل تريد حذف هذا الريل؟ ما تقدر تسترجع الريل بعد الحذف.',
//   Lkeys.inviteSomeone: 'دعوة شخص ما',
//   Lkeys.shareThisActivity: 'شارك هذا النشاط',

//   Lkeys.leaveThisActivity: 'اترك هذا النشاط',
//   Lkeys.roomSettings: 'إعدادات الغرفة',
//   Lkeys.joinRequests: 'طلبات الانضمام',
//   Lkeys.requests: 'الطلبات',
//   Lkeys.activityMembers: 'أعضاء النشاط',
//   Lkeys.deleteThisActivity: 'احذف هذا النشاط',
//   Lkeys.createdBy: 'أنشأ بواسطة:',
//   Lkeys.createdOn: 'تم إنشاؤه في:',
//   Lkeys.leaveRoomDesc: 'هل تريد مغادرة هذه الغرفة؟ ما تقدر ترسل رسائل أو تستكشف بعد ما تغادر.',
//   Lkeys.areYouSure: 'هل أنت متأكد؟',
//   Lkeys.leaveActivity: 'غادر النشاط',
//   Lkeys.leave : 'مغادرة',
//   Lkeys.logoutDesc: 'هل تريد تسجيل الخروج من هذا الحساب؟',
//   Lkeys.deleteAccDesc: 'هل تريد حذف هذا الحساب؟ ما تقدر تسترجع بيانات الحساب بعد الحذف.',
//   Lkeys.searchHere: 'ابحث هنا..',
//   Lkeys.remove: 'إزالة',
//   Lkeys.invite: 'دعوة',
//   Lkeys.edit: 'تعديل',
//   Lkeys.invited: 'مدعو',
//   Lkeys.removeFromRoom: 'إزالة من الغرفة',
//   Lkeys.makeAdmin: 'جعل مشرف',
//   Lkeys.selectReason: 'حدد السبب',
//   Lkeys.tellUsMore: 'أخبرنا المزيد',
//   Lkeys.submitReport: 'إرسال التقرير',
//   Lkeys.deleteRoomDesc: 'هل تريد حذف هذه الغرفة؟ ما تقدر تسترجع الغرفة بعد الحذف.',
//   Lkeys.allMembers: 'كل الأعضاء',
//   Lkeys.admins: 'المشرفين',
//   Lkeys.forYou: 'لك',
//   Lkeys.forYouActivitiesNoData: 'ما في أنشطة، تابع ناس عشان تشوف أنشطتهم',
//   Lkeys.previousActivitiesNoData: 'ما في أنشطة سابقة',
//   Lkeys.platform: 'منصة',
//   Lkeys.search: 'بحث',
//   Lkeys.update: 'تحديث',

//   Lkeys.profileVerificationDesc: 'الحسابات اللي تم التحقق منها فيها علامة صح جنب الاسم، تثبت انهم شخصيات عامة أو مشهورة.',
//   Lkeys.documentType: 'نوع الوثيقة',
//   Lkeys.selectDocument: 'حدد الوثيقة',
//   Lkeys.yourSelfie: 'صورتك الشخصية',
//   Lkeys.capture: 'التقاط',



//   //===================
//   Lkeys.locationPermissionRequired : 'صلاحية الموقع مطلوبة',
// Lkeys.locationServicesDisabled : 'خدمات الموقع معطلة',
//   Lkeys.locationDisclosure: 'مطلوب الوصول إلى الموقع',

// Lkeys.locationDisclosureTitle: 'لماذا يحتاج icar إلى موقعك؟',
// Lkeys.locationDisclosureDesc: 'يقوم icar بجمع بيانات الموقع لتمكين مشاركة موقع النشاط والأماكن القريبة، حتى عندما يكون التطبيق مغلقًا أو في الخلفية. هذه البيانات ضرورية لإظهار أصدقائك أين تحدث أنشطتك في الوقت الحقيقي.',
// Lkeys.locationDisclosureButton: 'فهمت',
// Lkeys.locationDisclosureButton2: 'إلغاء',

// Lkeys.locationDisclosurePermDeniedButton: 'فتح الإعدادات',
// Lkeys.locationDisclosurePermDeniedTitle: 'تم رفض الوصول إلى الموقع',
// Lkeys.locationDisclosurePermDeniedDesc: 'يجب الوصول إلى الموقع لاستخدام هذه الميزة. يرجى تمكين الوصول إلى الموقع من إعدادات الجهاز.',

// //=======================

//   Lkeys.pleaseSelectImage: 'الرجاء اختيار صورة',
//   Lkeys.postAddedSuccessfully: 'تم إضافة المنشور بنجاح',
//   Lkeys.deletePostDesc: 'ما تقدر تسترجع المنشور بعد الحذف. هل تريد حذف المنشور؟',
//   Lkeys.bio:'نبذة',
//   Lkeys.writeSomethingAboutYourSelf: 'اكتب شيء عن نفسك',
//   Lkeys.profileUpdatedSuccessfully: 'تم تحديث الملف الشخصي بنجاح',
//   Lkeys.pleaseEnterRoomName: 'الرجاء إدخال اسم الغرفة',
//   Lkeys.pleaseEnterDescription: 'الرجاء إدخال وصف قصير',
//   Lkeys.pleaseSelectAtLeast2Interests: 'حدد اهتمامين على الأقل',
  
//   Lkeys.reportUser: 'إبلاغ عن مستخدم',
//   Lkeys.reportReel: 'إبلاغ عن ريل',
//   Lkeys.reportActivity: 'إبلاغ عن نشاط',
//   Lkeys.reportStory: 'إبلاغ عن قصة',
//   Lkeys.reportComment: 'إبلاغ عن تعليق',
//   Lkeys.reportEvent: 'إبلاغ عن حدث',




//   Lkeys.likes: 'الإعجابات',
//   Lkeys.done:'تم',
//   Lkeys.noLikes: 'ما في إعجابات، كن أول من يعجب',
//   Lkeys.likedBy: 'أعجب به',
//   Lkeys.reportAddedSuccessfully: 'تم إرسال التقرير بنجاح',
//   Lkeys.pleaseEnterFullName: 'الرجاء إدخال الاسم الكامل',
//   Lkeys.pleaseSelectDocument: 'الرجاء تحديد الوثيقة',
//   Lkeys.pleaseEnterYourSelfie: 'الرجاء إدخال صورتك الشخصية',
//   Lkeys.profileVerificationRequestSent: 'تم إرسال طلب التحقق بنجاح',
//   Lkeys.verificationPending: 'طلب التحقق قيد الانتظار',

//   Lkeys.register: 'سجل',
//   Lkeys.iHaveAnAccount: 'عندي حساب',
//   Lkeys.signIn: 'تسجيل الدخول',
//   Lkeys.forgotPassword: 'نسيت كلمة السر؟',
//   Lkeys.forgotPasswordDisc: 'ادخل الإيميل اللي سجلت فيه حسابك، وسنرسل لك رابط إعادة تعيين كلمة المرور',
//   Lkeys.reset: 'إعادة ضبط',
//   Lkeys.continue_: 'استمر',
//   Lkeys.doNtHaveAnAccount: 'ما عندي حساب',
//   Lkeys.signUp: 'سجل',
//   Lkeys.passwordMismatched: 'كلمة المرور غير متطابقة',
//   Lkeys.verificationLinkSent: 'تم إرسال رابط التحقق على إيميلك، الرجاء التحقق من الإيميل',
//   Lkeys.pleaseVerifyToSignIn: 'يرجى التحقق من الإيميل لتسجيل الدخول.',
//   Lkeys.linkSendToReset: 'تم إرسال رابط إعادة تعيين كلمة المرور إلى إيميلك',
//   Lkeys.noDataFound: 'ما في بيانات',
//     Lkeys.noActivtiesFound: 'ما في نشاطات',
//   Lkeys.noUsersFound: 'ما في مستخدمين',
//   Lkeys.noEventsFound : 'ما في أحداث',
//   Lkeys.someThingWentWrong: 'في شيء خطأ',
//   Lkeys.invitedSuccessfully: 'تمت الدعوة بنجاح',
//   Lkeys.roomCreatedSuccessfully: 'تم إنشاء الغرفة بنجاح',
//   Lkeys.roomUpdatedSuccessfully: 'تم تحديث الغرفة بنجاح',
//   Lkeys.owner: 'المالك',
//   Lkeys.unBlock: 'إلغاء الحظر',
//   Lkeys.blockDesc: 'بعد حظر المستخدم، ما تقدر تتواصل معه.',
//   Lkeys.unblockDesc: 'إذا تبغى تتواصل معه، لازم تلغي الحظر.',
//   Lkeys.youAreBlocked: 'المستخدم هذا حظرك، فما تقدر تتواصل معه.',
//   Lkeys.deleteChat: 'حذف الدردشة',
//   Lkeys.deleteChatDesc: 'بعد حذف الدردشة، ما تقدر تسترجع رسائلك.',
//   Lkeys.markAsRead: 'وضع علامة مقروء',
//   Lkeys.markAsUnread: 'وضع علامة كغير مقروءة',
//   Lkeys.clearChat: 'مسح الدردشة',
//   Lkeys.clearChatDesc: 'بعد ما تمسح الدردشة، ما تقدر تسترجع رسائلك.',
//   Lkeys.deleteActivityDesc: 'بعد حذف النشاط، ما تقدر تسترجع بيانات النشاط. هل تريد حذف النشاط؟',
//   Lkeys.deleteEventDesc: 'بعد حذف الحدث، ما تقدر تسترجع بيانات الحدث. هل تريد حذف الحدث؟',
//   Lkeys.deleteEvent: 'حذف الحدث',
//   Lkeys.image: 'صورة',
//   Lkeys.video: 'فيديو',
//   Lkeys.howDoYouWant: 'ماذا تريد تشارك؟',
//   Lkeys.send: 'إرسال',
//   Lkeys.suggested: 'مقترح',
//   Lkeys.you: 'أنت',
//   Lkeys.use: 'استخدام',
//   Lkeys.retake: 'إعادة الالتقاط',
//   Lkeys.create: 'إنشاء',
//   Lkeys.pleaseEnterUsername: 'ادخل اسم المستخدم',
//   Lkeys.noPosts: 'ما في منشورات',
//   Lkeys.createPost: 'أنشئ منشور',
//   Lkeys.createStory: 'أنشئ قصة',
//   Lkeys.youCanNotSelectMoreThan: 'ما تقدر تحدد أكثر من',
//   Lkeys.deleteCommentDisc: 'هل تريد حذف هذا التعليق؟ ما تقدر تسترجعه بعد الحذف.',
//   Lkeys.rejectInvitationDisc: 'هل تريد رفض الدعوة؟ ما تقدر تسترجع الدعوة بعد الرفض.',
//   Lkeys.removeFromAdmin: 'هل تريد إزالة هذا المشرف؟',
//   Lkeys.removeTagedUserFromActivity: 'هل تريد إزالة إشارة هذا المستخدم من النشاط؟ ما تقدر تسترجع الإشارة بعد الحذف.',
//   Lkeys.removeUserFromActivity: 'هل تريد إزالة هذا المستخدم من النشاط؟ ما تقدر تسترجع المستخدم بعد الحذف.',
//   Lkeys.hasAcceptedYourJoinRequestOfRoom: 'قبل طلب انضمامك للغرفة',
//   Lkeys.hasJoinedYourRoom: 'انضم لغرفتك',
//   Lkeys.hasRequestedToJoinYourRoom: 'طلب الانضمام لغرفتك',
//   Lkeys.hasAcceptedYourInvitationOfRoom: 'قبل دعوتك للغرفة',
//   Lkeys.hasInvitedToRoom: 'تمت دعوته للغرفة',
//   Lkeys.hasLikedYourPost: 'أعجب بمنشورك',
//   Lkeys.hasCommentedToYourPost: 'علق على منشورك',
//   Lkeys.hasStartedFollowingYou: 'بدأ بمتابعتك',
//   Lkeys.faqS: 'الأسئلة الشائعة',
//   Lkeys.blockList: 'الملفات الشخصية المحظورة',
//   Lkeys.storyDeleteDisc: 'هل تريد حذف هذه القصة؟ ما تقدر تسترجع القصة بعد الحذف.',
//   Lkeys.storyDelete: 'حذف القصة',
//   Lkeys.yourAccountBlocked: 'تم حظر حسابك!',
//   Lkeys.yourAccountBlockedDisc: 'المشرف حظر حسابك. تواصل معنا على الإيميل التالي لحل المشكلة.',
//   Lkeys.yesterday: 'أمس',
//   Lkeys.anHourAgo: 'قبل ساعة',
//   Lkeys.aMinuteAgo: 'منذ دقيقة',
//   Lkeys.justNow: 'الآن',
//   Lkeys.hr: 'س',
//   Lkeys.minute: 'د',
//   Lkeys.languages: 'اللغات',
//   Lkeys.selectDate: 'حدد التاريخ',
//   Lkeys.selectTime: 'حدد الوقت',
//   Lkeys.waitFor: 'انتظر لـ',
//   Lkeys.secondsToResendTheCode: 'ثانية لإعادة إرسال الرمز',
//   Lkeys.showLess: 'عرض أقل',
//   Lkeys.showMore: 'عرض المزيد',
//   Lkeys.rejectChatRequest: 'رفض طلب الدردشة',
//   Lkeys.verificationDocumentTitle: 'عنوان التحقق من الوثيقة',
//   Lkeys.verificationDocumentDesc: 'وصف التحقق من الوثيقة',
//   Lkeys.verificationSubscriptionTitle: 'عنوان الاشتراك للتحقق',
//   Lkeys.verificationSubscriptionDesc: 'وصف الاشتراك للتحقق',
//   Lkeys.weekly: 'أسبوعي',
//   Lkeys.monthly: 'شهري',
//   Lkeys.annual: 'سنوي',
//   Lkeys.lifetime: 'مدى الحياة',
//   Lkeys.sixMonth: 'ستة أشهر',
//   Lkeys.threeMonth: 'ثلاثة أشهر',
//   Lkeys.twoMonth: 'شهرين',
//   Lkeys.subscriptionDesc: 'وصف الاشتراك',
//   Lkeys.weAreOnlyAllow: 'نحن نسمح فقط بـ',

//   Lkeys.unMuteNotification: 'إلغاء كتم الإشعارات',
//   Lkeys.method2: 'الطريقة الثانية',
//   Lkeys.method1: 'الطريقة الأولى',
//   Lkeys.pleaseConfigureSubscription: 'يرجى تكوين الاشتراك',
//   Lkeys.private: 'خاص',
//   Lkeys.public: 'عام',
//   Lkeys.optionalImages: 'الصور (اختياري)',

//   Lkeys.newActivity: 'نشاط جديد',
//   Lkeys.editActivity: 'تعديل النشاط',
//   Lkeys.activityTitle: 'عنوان النشاط',
//   Lkeys.activityTitleHint: 'ادخل عنوان النشاط',

//   Lkeys.activityDescription: '(اختياري) وصف النشاط',
//   Lkeys.activityDescriptionHint: 'ادخل وصف النشاط',
//   Lkeys.activityType: 'نوع النشاط',
//   Lkeys.activityTypeHint: 'حدد نوع النشاط',
//   Lkeys.activityStartDate: 'تاريخ بدء النشاط',
//   Lkeys.activityStartDateHint: 'حدد تاريخ بدء النشاط',
//   Lkeys.activityEndDate: 'تاريخ نهاية النشاط',
//   Lkeys.activityEndDateHint: 'حدد تاريخ نهاية النشاط',
//   Lkeys.activityStartTime: 'وقت بدء النشاط',
//   Lkeys.activityStartTimeHint: 'حدد وقت بدء النشاط',
//   Lkeys.activityEndTime: 'وقت نهاية النشاط',
//   Lkeys.activityEndTimeHint: 'حدد وقت نهاية النشاط',
//   Lkeys.activityLocation: 'موقع النشاط',
//   Lkeys.activityLocationHint: 'ادخل موقع النشاط',
//   Lkeys.activityPrice: 'سعر النشاط',
//   Lkeys.activityPriceMessage:'سيتم إحتساب سعر الإشتراك للفرد الواحد تلقائياً',
//   Lkeys.activityCostHint: 'ادخل سعر النشاط',
//   Lkeys.activityParticipants: 'عدد المشاركين',
//   Lkeys.activityParticipantsHint: 'ادخل عدد المشاركين',
//   Lkeys.autoAcceptParticipants: 'قبول المشاركين تلقائيًا',
//   Lkeys.createActivity: 'إنشاء النشاط',

//   Lkeys.ras: 'ر.س',
//   Lkeys.free: 'مجانا',
//   Lkeys.rasforEach:'ر.س لكل فرد',
//    Lkeys.selectLocation: 'حدد الموقع',


//   //=========
// Lkeys.newEvent: 'فعالية جديدة',
// Lkeys.eventDetails: 'تفاصيل الفعالية',
// Lkeys.bookYourTicket: 'احجز تذكرتك',
// Lkeys.editEvent: 'تعديل الفعالية',
// Lkeys.eventTitle: 'عنوان الفعالية',

// Lkeys.eventTitleHint: 'أدخل عنوان الفعالية',
// Lkeys.eventUrl: 'رابط الفعالية',
// Lkeys.eventUrlHint: 'أدخل رابط الفعالية',
// Lkeys.eventNotes : 'ملاحظات',
// Lkeys.eventNoteHint: 'أدخل ملاحظات',
// Lkeys.eventDescription: 'وصف الفعالية (اختياري)',
// Lkeys.eventDescriptionHint: 'أدخل وصف الفعالية',
// Lkeys.eventType: 'نوع الفعالية',
// Lkeys.eventCity: 'مدينة الفعالية',
// Lkeys.eventCityHint: 'اختر مدينة الفعالية',
// Lkeys.eventState: 'منطقة الفعالية',
// Lkeys.eventStateHint: 'اختر منطقة الفعالية',

// Lkeys.eventTypeHint: 'حدد نوع الفعالية',
// Lkeys.eventStartDate: 'تاريخ بدء الفعالية',
// Lkeys.eventStartDateHint: 'حدد تاريخ بدء الفعالية',
// Lkeys.eventEndDate: 'تاريخ نهاية الفعالية',
// Lkeys.eventEndDateHint: 'حدد تاريخ نهاية الفعالية',
// Lkeys.eventStartTime: 'وقت بدء الفعالية',
// Lkeys.eventStartTimeHint: 'حدد وقت بدء الفعالية',
// Lkeys.eventEndTime: 'وقت نهاية الفعالية',
// Lkeys.eventEndTimeHint: 'حدد وقت نهاية الفعالية',
// Lkeys.eventLocation: 'موقع الفعالية',
// Lkeys.eventLocationHint: 'أدخل موقع الفعالية',
// Lkeys.eventPrice: 'السعر',

// Lkeys.createEvent: 'إنشاء فعالية',

// //============
//   Lkeys.organizerRegistration: 'تسجيل منظم',
//   Lkeys.organizerRegistrationDesc: 'عبي النموذج تحت عشان تصير منظم وتبدأ إنشاء الفعاليات.',

//   Lkeys.orgnanizerPendingMessage: 'طلب تسجيلك كمنظم قيد المراجعة، بنرجع لك قريب.',
//   Lkeys.orgnanizerSuccessRegistration: 'تم التسجيل بنجاح',
//   Lkeys.orgnanizerSuccessRegistrationMessage: 'شكرًا لتسجيلك كمنظم، بنراجع طلبك وبنرجع لك قريب.',

//   Lkeys.businessName: 'الاسم التجاري',
//   Lkeys.businessNameHint: 'ادخل الاسم التجاري حسب السجل التجاري',

//   Lkeys.organizerLogo: 'الشعار',
//   Lkeys.organizerLogoHint: 'ارفع شعار الشركة أو النشاط',
  
//   Lkeys.crFile: 'ملف السجل التجاري (PDF)',
//   Lkeys.crFileHint: 'ارفع ملف السجل التجاري',
//   Lkeys.crNumber: 'رقم السجل التجاري',
//   Lkeys.crNumberHint: 'ادخل رقم السجل التجاري',

//   Lkeys.selectBusinessType: 'حدد نوع النشاط',
//   Lkeys.selectBusinessTypeHint: 'حدد نوع النشاط',
//   Lkeys.selectCity: 'حدد المدينة',
//   Lkeys.selectCityHint: 'حدد المدينة',



//   Lkeys.coins : 'نقاط',
//   Lkeys.yourCoins: 'نقاطك',
//   Lkeys.youHave: 'لديك',
//   Lkeys.buyCoins : 'شراء نقاط',
//   Lkeys.buyCoinsDesc :'اشتري النقاط لتستطيع إضافة المزيد من الانشطة',
// };

// const englishStrings = {

//   Lkeys.newActivity: 'New Activity',
//   Lkeys.editActivity: 'Edit Activity',
//   Lkeys.activityTitle: 'Activity Title',
//   Lkeys.activityTitleHint: 'Enter Activity Title',
//   Lkeys.activityDescription: 'Activity Description (Optional)',
//   Lkeys.activityDescriptionHint: 'Enter Activity Description',
//   Lkeys.activityType: 'Activity Type',
//   Lkeys.mentions: 'Mentions',
//   Lkeys.activityTypeHint: 'Select Activity Type',
//   Lkeys.activityStartDate: 'Activity Start Date',
//   Lkeys.activityStartDateHint: 'Select Activity Start Date',
//   Lkeys.activityEndDate: 'Activity End Date',
//   Lkeys.activityEndDateHint: 'Select Activity End Date',
//   Lkeys.activityStartTime: 'Activity Start Time',
//   Lkeys.activityStartTimeHint: 'Select Activity Start Time',
//   Lkeys.activityEndTime: 'Activity End Time',
//   Lkeys.activityEndTimeHint: 'Select Activity End Time',
//   Lkeys.activityLocation: 'Activity Location',
//   Lkeys.activityLocationHint: 'Enter Activity Location',
//   Lkeys.activityPrice:  'Price',
//     Lkeys.activityPriceMessage:'The subscription price per person will be calculated automatically',

//   Lkeys.activityCostHint: 'Enter Activity Price',
//   Lkeys.activityParticipants: 'Participants',
//   Lkeys.activityParticipantsHint: 'Enter Activity Participants Count',
//   Lkeys.autoAcceptParticipants: 'Auto Accept Participants',
//   Lkeys.createActivity: 'Create Activity',
//     Lkeys.pressBackAgainToExit : 'Press back again to exit',
//   Lkeys.ras: 'SAR',
//   Lkeys.free: 'Free',
//   Lkeys.rasforEach:'SAR/Per Person', 
//   Lkeys.from: 'From',
//   Lkeys.to: 'To',
//   Lkeys.startAt: 'Start At',
//   Lkeys.endAt: 'End At',
//    Lkeys.resendCode: 'Resend Code',
//    Lkeys.selectLocation: 'Select Location',
// //===============================

// Lkeys.locationDisclosure: 'Location Access Required',
// Lkeys.locationPermissionRequired : 'Location Permission Required',
// Lkeys.locationServicesDisabled : 'Location services are disabled. Please enable them to proceed',
// Lkeys.locationDisclosureTitle:    'Why does icar need your location?',
// Lkeys.locationDisclosureDesc:      'icar collects location data to enable activity location sharing and nearby places, even when the app is closed or in the background. This data is necessary for showing your friends where your activities are happening in real-time.',
// Lkeys.locationDisclosureButton:    'Got it',
// Lkeys.locationDisclosureButton2:    'Cancel',

// Lkeys.locationDisclosurePermDeniedButton: 'Enable Location Access',
// Lkeys.locationDisclosurePermDeniedTitle: 'Location Access Denied',
// Lkeys.locationDisclosurePermDeniedDesc: 'You have denied location access. Please enable location access in your settings to continue using icar.',





// //=================
// Lkeys.newEvent: 'New Event',
// Lkeys.eventDetails: 'Event Details',
// Lkeys.bookYourTicket: 'Book Your Ticket',
// Lkeys.editEvent: 'Edit Event',
// Lkeys.eventTitle: 'Event Title',
// Lkeys.eventTitleHint: 'Enter Event Title',
// Lkeys.eventUrl: 'Event URL',
// Lkeys.eventUrlHint: 'Enter Event URL',
// Lkeys.eventNotes : 'Event Notes',
// Lkeys.eventNoteHint: 'Enter Event Notes',
// Lkeys.eventDescription: 'Event Description (Optional)',
// Lkeys.eventDescriptionHint: 'Enter Event Description',
// Lkeys.eventType: 'Event Type',
// Lkeys.eventCity: 'Event City',
// Lkeys.eventCityHint: 'Select Event City',
// Lkeys.eventState: 'Event State',
// Lkeys.users : 'Users',
// Lkeys.eventStateHint: 'Select Event State',

// Lkeys.eventTypeHint: 'Select Event Type',
// Lkeys.eventStartDate: 'Event Start Date',
// Lkeys.eventStartDateHint: 'Select Event Start Date',
// Lkeys.eventEndDate: 'Event End Date',
// Lkeys.eventEndDateHint: 'Select Event End Date',
// Lkeys.eventStartTime: 'Event Start Time',
// Lkeys.eventStartTimeHint: 'Select Event Start Time',
// Lkeys.eventEndTime: 'Event End Time',
// Lkeys.eventEndTimeHint: 'Select Event End Time',
// Lkeys.eventLocation: 'Event Location',
// Lkeys.eventLocationHint: 'Enter Event Location',
// Lkeys.eventPrice: 'Price',
// Lkeys.createEvent: 'Create Event',

//   //==================================================================================================//
//   Lkeys.no: 'No',

//     Lkeys.pm: 'PM',
//   Lkeys.am: 'AM',


//   Lkeys.yes: 'Yes',
//   Lkeys.next: 'Next',
//   Lkeys.submit: 'Submit',
//   Lkeys.login: 'Login',
//   Lkeys.email: 'E-Mail',
//   Lkeys.signup: 'Signup',
//   Lkeys.logout: 'Logout',
//   Lkeys.success: 'Success',
//   Lkeys.addPhotoOrAvatar: 'Add Photo or Avatar',
//   Lkeys.accountData: 'Account Data',
//   Lkeys.enterAccountDataToContinue: 'Enter account data to continue',
//   // TextKeys.name: 'Name',
//   Lkeys.fullName: 'Full Name',
//   Lkeys.nickname: 'Nick Name',
//   Lkeys.gender: 'Gender',
//   Lkeys.male: 'Male',
//   Lkeys.female: 'Female',
//   Lkeys.birthDate: 'Date of Birth',
//   Lkeys.phoneNumber: 'Phone Number',


//     Lkeys.reportUser: 'Report User',
//   Lkeys.reportReel: 'Report Reel',
//   Lkeys.reportActivity: 'Report Activity',
//   Lkeys.reportStory: 'Report Story',
//   Lkeys.reportComment: 'Report Comment',
//   Lkeys.reportEvent: 'Report Event',

//   Lkeys.save: 'Save',
//   Lkeys.saved: 'Saved',
//   Lkeys.chooseGender: 'Choose the Gender',
//   Lkeys.phoneRequired: 'Phone number is required',
//   Lkeys.phoneTooShort: 'Phone number is too short',
//   Lkeys.phoneTooLong: 'Phone number is too long',
//   Lkeys.phoneNoStart0: 'Phone number should not start with 0',
//   Lkeys.phoneShouldStart5: 'Phone number should start with 5',
//   Lkeys.phoneInvalid: 'Please enter a valid phone number',
//   Lkeys.phoneNumberHint: 'Enter Your Phone Number',
//   Lkeys.continueText: 'Continue',
//   Lkeys.password: 'Password',
//   Lkeys.confirmPassword: 'Confirm Password',
//   Lkeys.dontHaveAnAccount: 'Don\'t have an account?',
//   Lkeys.getStarted: 'Get Started',
//   Lkeys.forgetPassword: 'Forget Password?',

//     Lkeys.coins : 'Coins',
//   Lkeys.yourCoins:'Your Coins',
//   Lkeys.youHave:'You have',
//   Lkeys.buyCoins : 'Buy Coins',
//   Lkeys.buyCoinsDesc :'Buy More Coins, so you can add more acivities',

//   Lkeys.notVerified: 'Not verified yet',
//   Lkeys.loading: 'loading',
//   Lkeys.successVerifyYourEmail: 'Your email has been verified successfully',
//   Lkeys.nothingFound: 'Nothing found',
//   Lkeys.tryAgain: 'Try Again',
//   Lkeys.thereIsSomethingError: 'There is something error.. Try later',
//   Lkeys.emailCannotEmpty: 'Email cannot be empty',
//   Lkeys.invalidEmailFormat: 'Invalid email format',
//   Lkeys.shortPasswordError: 'The password must be greater than 8 characters',
//   Lkeys.longPasswordError: 'Too long password',
//   Lkeys.passwordsDoesNotMatch: 'Password does not match',
//   Lkeys.noRecordFound: 'No record found',
//   Lkeys.requiredField: 'Required field',
//   Lkeys.nameCannotEmpty: 'Name cannot be empty',
//   Lkeys.phoneCannotEmpty: 'Phone number cannot be empty',
//   Lkeys.emailNotFound: 'This email does not exist',
//   Lkeys.otpTitle: 'CODE',
//   Lkeys.otpSubTitle: 'Verification',
//   Lkeys.viewers: 'Viewers',
//   Lkeys.otpMessage: 'Enter the verification code sent to',
//   Lkeys.alert: 'Alert',
//   Lkeys.ohSnap: 'Oh Snap',
//   Lkeys.emailSent: 'Hurray!!! Email is on its way.',
//   Lkeys.congratulations: 'Congratulations',
//   Lkeys.emailLinkToResetPassword: 'Email Link To Reset Password',
//   Lkeys.accountCreateVerifyEmail: 'Account Create Verify Email',
//   Lkeys.welcomeBack: 'Welcome Back',
//   Lkeys.loginSubTitle:
//       'Enter your phone number and join us in the world of activities and entertainment',
//   Lkeys.loginTitle: 'Welcome aboard!',
//   Lkeys.rememberMe: 'Remember Me?',
//   // TextKeys.dontHaveAnAccount: 'Don\'t have an Account',
//   Lkeys.enterYour: 'Enter your',
//   Lkeys.resetPassword: 'Reset Password',
//   Lkeys.or: 'OR',
//   Lkeys.connectWith: 'Connect With',
//   Lkeys.facebook: 'Facebook',
//   Lkeys.google: 'Google',
//   Lkeys.signUpTitle: 'Get On Board!',
//   Lkeys.signUpSubTitle: 'Create your profile to start your Journey.',
//   Lkeys.alreadyHaveAnAccount: 'Already have an Account',
//   Lkeys.forgetPasswordTitle: 'Make Selection!',
//   Lkeys.forgetPasswordSubTitle: 'Enter your email to reset your password.',
//   Lkeys.resetViaEMail: 'Reset via Mail Verification',
//   Lkeys.resetViaPhone: 'Reset via Phone Verification',
//   Lkeys.forgetPhoneSubTitle: 'Enter your registered Phone No to receive OTP',
//   Lkeys.forgetMailSubTitle: 'Enter your registered E-Mail to receive OTP',
//   Lkeys.emailVerificationTitle: 'Verify your email address',
//   Lkeys.emailVerificationSubTitle:
//       'We have just sent an email verification link on your email. Please check email and click on that link to verify your Email address. \n\n If not auto redirected after verification, click on the Continue button.',
//   Lkeys.resendEmailLink: 'Resend E-Mail Link',
//   Lkeys.backToLogin: 'Back to login',
//   Lkeys.backToProfile: 'Back to Profile',
//   Lkeys.profile: 'Profile',
//     Lkeys.organizer: 'Organizer',
//   Lkeys.becomeAnOrganizer: 'Become an Organizer',
//   Lkeys.anOrganizer: 'Organizer',
//   Lkeys.organizerProfile: 'Organizer Profile',
//   Lkeys.editProfile: 'Edit Profile',
//   Lkeys.logoutDialogHeading: 'Logout',
//   Lkeys.profileHeading: 'Mohammed Alsayani',
//   Lkeys.profileSubHeading: 'Mo7hammedalsayani@gmail.com',
//   Lkeys.menuLogout: 'Logout',
//   Lkeys.menuSettings: 'Settings',
//   Lkeys.menuInformation: 'Information',
//   Lkeys.menuBillingDetails: 'Billing Details',
//   Lkeys.menuUserManagement: 'User Management',
//   Lkeys.delete: 'Delete',
//   Lkeys.joined: 'Joined',
//   Lkeys.joinedAt: '31 May 2024',
//   Lkeys.private: 'Private',
//   Lkeys.public: 'Public',

//   ///validation
//   Lkeys.invalidNameFormat: 'Invalid name format',
//   Lkeys.invalidFormat: 'Invalid format',
//   Lkeys.shortUsernameError: 'Username must be greater than 3 characters',
//   Lkeys.longUsernameError: 'Username must be less than 10 characters',
//   Lkeys.invalidUsernameFormat:
//       'Invalid username format, only letters and numbers are allowed, it must start with @',

//   ///=================================================//
//   Lkeys.textChatDedicated: 'Text Chat Dedicated',
//   Lkeys.socialMedia: 'Social Media',
//   Lkeys.chatRoom: 'CHAT ROOMS',
//   Lkeys.selectTime: 'Select Time',
//   Lkeys.selectDate: 'Select Date',
//     Lkeys.edit: 'Edit',
//     Lkeys.optionalImages: 'Images (Optional)',
//   Lkeys.chatRoomDesc:
//       'Create, add interests, add a profile, share your room, and have tons of conversations on chat rooms.',
//   Lkeys.randomRoom: 'RANDOM CHATS',
//   Lkeys.randomRoomDesc:
//       'Find a random buddy according to your interests, send chat requests, and have fun',
//   Lkeys.craftYourProfile: 'CRAFT YOUR PROFILE',
//   Lkeys.craftYourProfileDesc:
//       'Find a random buddy according to your interests, send chat requests, and have fun',
//   Lkeys.createChatPost: 'CREATE TEXT POST',
//   Lkeys.createChatPostDesc:
//       'Post your thoughts or feelings on the public wall and let the public discuss, and increase your fans.',
//   Lkeys.letsStart: 'Let\'s Start',
//   Lkeys.signInTo: 'Sign in To',
//   Lkeys.continue1: 'Continue',
//   Lkeys.signInDesc:
//       'choose any of the methods below\nand sign in to continue using this app',
//   Lkeys.signInWithGoogle: 'Sign In With Google',
//   Lkeys.signInWithEmail: 'Sign In With Email',
//   Lkeys.signInWithApple: 'Sign In With Apple',
//   Lkeys.bySelectingAgree: 'By selecting Agree and continue below,',
//   Lkeys.iAgreeTo: 'I agree to ',
//   Lkeys.termsAndConditions: 'Terms and Conditions',
//   Lkeys.and: 'and',
//   Lkeys.privacyPolicy: 'Privacy Policy',
//   Lkeys.selectYour: 'Select Your',
//   Lkeys.select  : 'Select',
//   Lkeys.interests: 'Interests',
//   Lkeys.interestsDesc:
//       'Select some interests, based on\nwhich, we can prefer your chat rooms.',
//   Lkeys.setYour: 'Set Your',
//   Lkeys.username: 'Username',
//   ///////========================================
//   Lkeys.currentActivity: 'Current',
//   Lkeys.addActivity: 'Add Activity',
//   Lkeys.addEvent: 'Add Event',
//   Lkeys.addReel: 'Add Reel',
//   Lkeys.addStory: 'Add Story',
  
//   Lkeys.organizerRegistration: 'Organizer Registration',
//   Lkeys.organizerRegistrationDesc:
//       'Fill the form below to become an organizer and start creating Events',

//   Lkeys.orgnanizerPendingMessage: 'Your organizer registration is pending, we will review your application and get back to you soon.',
//   Lkeys.orgnanizerSuccessRegistration:'Organizer Registration Success',
//   Lkeys.orgnanizerSuccessRegistrationMessage: 'Thank you for registering as an organizer, we will review your application and get back to you soon.',


//   Lkeys.businessName: 'Business Name',
//   Lkeys.businessNameHint: 'Enter Your Business Name',

//   Lkeys.organizerLogo: 'Upload Business Logo',
//   Lkeys.organizerLogoHint: 'Upload Your Business Logo',
  
//   Lkeys.crFile: 'Upload CR File (PDF)',
//   Lkeys.crFileHint: 'Upload Your CR File',
//   Lkeys.crNumber: 'CR Number',
//   Lkeys.crNumberHint: 'Enter Your CR Number',


//   Lkeys.selectBusinessType: 'Select Business Type',
//   Lkeys.selectBusinessTypeHint: 'Choose Business Type',
//   Lkeys.selectCity: 'Select City',
//   Lkeys.selectCityHint: 'Choose City',


//   Lkeys.previousActivity: 'Previous',
//   Lkeys.all: 'All',
//   Lkeys.activity: 'Activity',
//   Lkeys.activities: 'Activities',
//   Lkeys.reels: 'Reels',
//   Lkeys.noReelsFound: 'No Reels Found',
//   Lkeys.sendMessage: 'Send Message',
//   Lkeys.uploadImage: 'Upload Image',
//   Lkeys.uploadImages: 'Upload Images',
//   Lkeys.noActivityfoundInYourAccount: 'No Activity found in your account, create your first activity',
//   Lkeys.noActivityfoundInThisAccount : 'No Activity found in this account',
//   Lkeys.whenPeopleTagYouInActivity: 'When people tag you in activity, you will see it here',
//   Lkeys.map: 'Map',
//   Lkeys.events: 'Events',
//   // LKeys.profile: 'Profile',

//   Lkeys.participants: 'Participants',
//   Lkeys.viewDetails: 'View Details',
//   Lkeys.multimedia: 'Multimedia',
//   Lkeys.description: 'Description',
//   Lkeys.openToJoin: 'Open to Join',
//   Lkeys.requestToJoin: 'Request to Join',
//   Lkeys.noParticipants: 'No Participants, Be the first to join',
//   Lkeys.noComments: 'No Comments, Be the first to comment',
//   Lkeys.noMultimedia: 'No Multimedia',
//   Lkeys.noDescription: 'No Description',
//   Lkeys.totalCost: 'Total Cost',
//   Lkeys.activitiyDetails: 'Activity Details',
//   Lkeys.details: 'Details',
//   //=====================================================
//   Lkeys.setUsernameDesc:
//       'Create an eye-catching username for you,\nIt will be shown on your profile',
//   Lkeys.thisUsernameIsNotAvailable: 'This username is not available',
//   Lkeys.thisUsernameIsAvailable: 'This username is available',
//   Lkeys.profilePicture: 'Profile Photo',
//   Lkeys.setProfileDesc: 'That’s great, Now\nlet us know how you look.',
//   Lkeys.feed: 'Feed',
//   Lkeys.rooms: 'Rooms',
//   Lkeys.randoms: 'Randoms',
//   Lkeys.chats: 'Chats',
//   Lkeys.chat: 'Chat',
//   Lkeys.d:'d',

//   Lkeys.exit: 'Exit',
//   Lkeys.exitAppDesc: 'Do you want to exit the app?',

//   Lkeys.comments: 'Comments',
//   Lkeys.writeSomething: 'Write Something',
//   Lkeys.replyingTo: 'Replying to',
//   Lkeys.showReply: 'Show Reply',
//   Lkeys.showReplies: 'Show Replies',
//   Lkeys.hideReplies: 'Hide Replies',
//   Lkeys.reply: 'Reply',
//   Lkeys.replies: 'Replies',
//   Lkeys.report: 'Report',
//   Lkeys.share: 'Share',
//   Lkeys.exploreBy: 'Explore by',
//   Lkeys.members: 'Members',
//   Lkeys.member : 'Member',
//   Lkeys.roomsBy: 'Rooms by',

//   Lkeys.requested: 'Requested',
//   Lkeys.cancelRequest: 'Cancel Request',
//   Lkeys.requestedFailed: 'Request Failed',
//   Lkeys.requestToJoinThisActivity: 'Request To Join This Activity',
//   Lkeys.requestToJoinDesc:
//       'Click the button below and request to join this chat room. You will be added to it once admin approves our request.',
//   Lkeys.joinThisActivity: 'Join This Activity',
//   Lkeys.searching: 'Searching',
//   Lkeys.searchingDesc:
//       'Searching profiles randomly\nbased on your interests, send them\nrequest and enjoy chatting with strangers',
//   Lkeys.found: 'Found',
//   Lkeys.waitFor: 'wait for',
//   Lkeys.secondsToResendTheCode: 'seconds to resend the code',

//   Lkeys.viewFullProfile: 'View Full Profile',
//   Lkeys.followers: 'Followers',
//   Lkeys.follow: 'Follow',
//   Lkeys.following: 'Following',
//   Lkeys.unFollow: 'Unfollow',
//     Lkeys.followBack: 'Follow Back',

//   Lkeys.profileSetting: 'Profile Settings',

//   Lkeys.roomsYouOwn: 'Rooms You Own',
//   Lkeys.roomsInvitation: 'Room Invitations',
//   Lkeys.notification: 'Notifications',
//   Lkeys.profileVerification: 'Profile Verification',
//   Lkeys.pushNotification: 'Push Notifications',
//   Lkeys.pushNotificationDesc:
//       'Keep it On, if you want to receive notifications',
//   Lkeys.getInvitedToRooms: 'Get Invited To Rooms',
//   Lkeys.getInvitedToRoomsDesc:
//       'Room admins can send you invitation to join chat rooms if you keep it on',
//   Lkeys.helpSupport: 'Help & Support',
//   Lkeys.logOut: 'Log out',
//   Lkeys.deleteMyAcc: 'Delete My Account',
//   Lkeys.version: 'version',
//   Lkeys.createNewRoom: 'Create New Room',
//   Lkeys.selectProfileImage: 'Select Profile Image',
//   Lkeys.selectBackgroundImage: 'Select Background Image',
//   Lkeys.roomName: 'Room Name',
//   Lkeys.shortDescription: 'Short Description',
//   Lkeys.selectTag: 'Select Tag',
//   Lkeys.tag: 'Tag',
//   Lkeys.tags: 'Tags',
//   Lkeys.tagUsers: 'Tag Users',
// Lkeys.cancel: 'Cancel',
//   Lkeys.usersTagged: 'Users Tagged',

//   Lkeys.createRoom: 'Create Room',
//   Lkeys.whatIsYourRoomAbout: 'What is your room about...',
//   Lkeys.makeRoomPublic: 'Make Room Public',
//   Lkeys.makeRoomPublicDesc:
//       'Keep it On, if you want to show your room to everyone publicly',
//   Lkeys.joinAfterRequest: 'Join After Request',
//   Lkeys.joinAfterRequestDesc:
//       'If this is on, New members need to request to join the room and admin needs to approve it.',
//   Lkeys.invitedBy: 'Invited By',
//   Lkeys.addPost: 'Add Post',
//   Lkeys.post: 'Post',
//   Lkeys.writeHere: 'Write here...',
//   Lkeys.block: 'Block',
//   Lkeys.reject: 'Reject',
//   Lkeys.accept: 'Accept',
//   Lkeys.acceptInvitation: 'Accept Invitation',
//   Lkeys.requestDesc: 'wants to chat with you, Approve it if you want to chat',
//   Lkeys.roomInfo: 'Room Info',
//   Lkeys.muteNotification: 'Mute Notification',
//   Lkeys.deleteActivity: 'Delete Activity',
//   Lkeys.deleteReel: 'Delete Reel',
//   Lkeys.deleteReelDesc: 'Do you want to delete this reel? You can not undo this action.',
//   Lkeys.inviteSomeone: 'Invite Someone',
//   Lkeys.shareThisActivity: 'Share This Activity',
//   Lkeys.leaveThisActivity: 'Leave This Activity',
//   Lkeys.roomSettings: 'Room Settings',
//   Lkeys.joinRequests: 'Join Requests',
//   Lkeys.requests: 'Requests',
//   Lkeys.activityMembers: 'Activity Members',
//   Lkeys.deleteThisActivity: 'Delete This Activity',
//   Lkeys.createdBy: 'Created By:',
//   Lkeys.createdOn: 'Created On:',
//   Lkeys.leaveRoomDesc:
//       'Do you want to exit this room? You won\'t be able to send messages or explore in this room once you leave this room.',
//   Lkeys.areYouSure: 'Are You Sure?',
//   Lkeys.leaveActivity: 'Leave Activity',
//   Lkeys.leave : 'Leave',
//   Lkeys.logoutDesc: 'Do you want to log in to this account?',
//   Lkeys.deleteAccDesc:
//       'Do you want to delete this account? You won\'t be able to restore the account or it\'s data.',
//   Lkeys.searchHere: 'Search Here..',
//   Lkeys.remove: 'Remove',
//   Lkeys.invite: 'Invite',
//   Lkeys.invited: 'Invited',
//   Lkeys.removeFromRoom: 'Remove From Room',
//   Lkeys.makeAdmin: 'Make Admin',
//   Lkeys.selectReason: 'Select Reason',
//   Lkeys.tellUsMore: 'Tell us more',
//   Lkeys.submitReport: 'Submit Report',
//   Lkeys.deleteRoomDesc:
//       'Do you want to delete this room? You won\'t be able to restore the room or it\'s data.',
//   Lkeys.allMembers: 'All Members',
//   Lkeys.admins: 'Admins',
//   Lkeys.forYou: 'For You',
//   Lkeys.forYouActivitiesNoData: 'No activities found, try to follow some users',
//   Lkeys.previousActivitiesNoData: 'No previous activities found',
//   Lkeys.platform: 'Platform',
//   Lkeys.search: 'Search',
//   Lkeys.update: 'Update',

//   Lkeys.profileVerificationDesc:
//       'Verified accounts have ticks next to their names to show that we have confirmed they are the real presence of public figures or celebrities.',
//   Lkeys.documentType: 'Document Type',
//   Lkeys.selectDocument: 'Select Document',
//   Lkeys.yourSelfie: 'Your Selfie',
//   Lkeys.capture: 'Capture',

//   Lkeys.pleaseSelectImage: 'Please select a image',
//   Lkeys.postAddedSuccessfully: 'Post added successfully',
//   Lkeys.deletePostDesc:
//       'You can not undone or get back your post. Do you want to delete your post?',
//   Lkeys.bio: 'Bio',
//   Lkeys.writeSomethingAboutYourSelf: 'Write something about yourself',
//   Lkeys.profileUpdatedSuccessfully: 'Profile Successfully Updated',
//   Lkeys.pleaseEnterRoomName: 'Please enter the room name',
//   Lkeys.pleaseEnterDescription: 'Please enter a short description',
//   Lkeys.pleaseSelectAtLeast2Interests: 'Please select at least 2 interests',

//   Lkeys.likes: 'Likes',
//   Lkeys.done :'Done',
//   Lkeys.noLikes: 'No Likes found, Be the first to like',
//   Lkeys.likedBy: 'Liked By',
//   Lkeys.reportAddedSuccessfully: 'Report submitted',
//   Lkeys.pleaseEnterFullName: 'Please enter a full name',
//   Lkeys.pleaseSelectDocument: 'Please select a document',
//   Lkeys.pleaseEnterYourSelfie: 'Please enter your selfie',
//   Lkeys.profileVerificationRequestSent:
//       'Profile verification request sent successfully',
//   Lkeys.verificationPending: 'A verification request has already been sent',

//   Lkeys.register: 'Register',
//   Lkeys.iHaveAnAccount: 'I have an account',
//   Lkeys.signIn: 'Sign in',
//   Lkeys.forgotPassword: 'Forgot Password?',
//   Lkeys.forgotPasswordDisc:
//       'Enter the email on which you have created an account. We will send a link to reset your password',
//   Lkeys.reset: 'Reset',
//   Lkeys.continue_: 'Continue',
//   Lkeys.doNtHaveAnAccount: 'I don\'t have an account',
//   Lkeys.signUp: 'Sign up',
//   Lkeys.passwordMismatched: 'Password is mismatched',
//   Lkeys.verificationLinkSent:
//       'The verification link has been to your email. Please verify the email from the inbox',
//   Lkeys.pleaseVerifyToSignIn:
//       'Please verify the email from the email inbox to sign in.',
//   Lkeys.linkSendToReset:
//       'The link to reset your password has been sent to your email',
//   Lkeys.noDataFound: 'No Data Found',
//   Lkeys.noActivtiesFound :'No Activities Found',
//   Lkeys.noUsersFound:'No Users Found',
//   Lkeys.noEventsFound :'No Events Found',

//   Lkeys.someThingWentWrong: 'Something went wrong',
//   Lkeys.invitedSuccessfully: 'Invited Successfully',
//   Lkeys.roomCreatedSuccessfully: 'Room Created Successfully',
//   Lkeys.roomUpdatedSuccessfully: 'Room Updated Successfully',
//   Lkeys.owner: 'Owner',
//   Lkeys.unBlock: 'Unblock',
//   Lkeys.blockDesc: 'After blocking the user, you can not chat with the user.',
//   Lkeys.unblockDesc: 'To chat with the user you have to unblock the user.',
//   Lkeys.youAreBlocked:
//       'This user blocks you, so you can not chat with the user.',
//   Lkeys.deleteChat: 'Delete chat',
//   Lkeys.deleteChatDesc:
//       'After deleting the chat, you can not restore your messages. Messages will be cleared from your account.',
//   Lkeys.markAsRead: 'Mark as read',
//   Lkeys.markAsUnread: 'Mark as unread',

//   Lkeys.clearChat: 'Clear Chat',  
//   Lkeys.clearChatDesc:
//       'After clearing the chat, you can not restore your messages. Messages will be cleared from your account.',
//   Lkeys.deleteActivityDesc:
//       'After deleting the activity you can not restore the activity or it\'s data. Do you want to delete the activity?',
//     Lkeys.deleteEventDesc: 'After deleting the event you can not restore the event or it\'s data. Do you want to delete the event?',
//   Lkeys.deleteEvent: 'Delete Event',
//   Lkeys.image: 'Image',
//   Lkeys.video: 'Video',
//   Lkeys.howDoYouWant: 'What do you want to share?',
//   Lkeys.send: 'Send',
//   Lkeys.suggested: 'Suggested',
//   Lkeys.you: 'You',
//   Lkeys.use: 'Use',
//   Lkeys.retake: 'Retake',
//   Lkeys.create: 'Create',
//   Lkeys.pleaseEnterUsername: 'Please enter a username',
//   Lkeys.noPosts: 'No Posts',
//   Lkeys.createPost: 'Create Post',
//   Lkeys.createStory: 'Create Story',
//   Lkeys.youCanNotSelectMoreThan: 'You can not select interests more than',
//   Lkeys.deleteCommentDisc:
//       'Do you want to delete this comment? You can not undo this process.',
//   Lkeys.rejectInvitationDisc:
//       'Do you want to reject the invitation? You can not undo this process.',
//   Lkeys.removeFromAdmin: 'Do you want to remove this admin from admin access?',
//   Lkeys.removeTagedUserFromActivity:
//       'Do you want to remove this tagged user from this Activity? You can not undo this process.',
//   Lkeys.removeUserFromActivity:
//       'Do you want to remove this user from this Activity? You can not undo this process.',
//   Lkeys.hasAcceptedYourJoinRequestOfRoom:
//       'has accepted your join request for the room',
//   Lkeys.hasJoinedYourRoom: 'has joined your room',
//   Lkeys.hasRequestedToJoinYourRoom: 'has requested to join your room',
//   Lkeys.hasAcceptedYourInvitationOfRoom:
//       'has accepted your invitation to the room',
//   Lkeys.hasInvitedToRoom: 'has invited to room',
//   Lkeys.hasLikedYourPost: 'has liked your post.',
//   Lkeys.hasCommentedToYourPost: 'has commented on your post.',
//   Lkeys.hasStartedFollowingYou: 'has started following you.',
//   Lkeys.faqS: 'FAQs',
//   Lkeys.blockList: 'Blocked Profiles',
//   Lkeys.storyDeleteDisc:
//       'Do you want to delete this story? You can not undo this process.',
//   Lkeys.storyDelete:
//       'Delete Story',
//   Lkeys.yourAccountBlocked: 'Your account has been blocked!',
//   Lkeys.yourAccountBlockedDisc:
//       'Admin has blocked your account. Please contact on email address below to proceed further in this matter.',
//   Lkeys.yesterday: 'Yesterday',
//   Lkeys.anHourAgo: 'an hour ago',
//   Lkeys.aMinuteAgo: 'a minute ago',
//   Lkeys.justNow: 'Just now',
//   Lkeys.hr: 'hr',
//   Lkeys.minute: 'minute',
//   Lkeys.languages: 'Languages',
//   Lkeys.showLess: 'Show Less',
//   Lkeys.showMore: 'Show More',
//   Lkeys.rejectChatRequest:
//       'Do you really to reject the chat request of the user.',
//   Lkeys.verificationDocumentTitle: 'Document Verification',
//   Lkeys.verificationDocumentDesc:
//       'Please note that document verification may take some time, so the process might be a bit slower than instant verification',
//   Lkeys.verificationSubscriptionTitle: 'Instant Verification',
//   Lkeys.verificationSubscriptionDesc:
//       "After subscribing, you'll be verified instantly. No need to wait through a long process",
//   Lkeys.weekly: 'Weekly',
//   Lkeys.monthly: 'Monthly',
//   Lkeys.annual: 'Annual',
//   Lkeys.lifetime: 'Lifetime',
//   Lkeys.sixMonth: '6 Month',
//   Lkeys.threeMonth: '3 Month',
//   Lkeys.twoMonth: '2 Month',
//   Lkeys.subscriptionDesc:
//       "Proceed with subscribing to the plan, and you'll be verified in just minutes with simple steps. Our plans are set for auto-renewal, so there's no need to worry about your subscription expiring",
//   Lkeys.weAreOnlyAllow: 'We only allow video that shorter than',
//   // LKeys.minute: 'minute !',
//   Lkeys.unMuteNotification: 'Unmute Notification',
//   Lkeys.method2: 'Method 2',
//   Lkeys.method1: 'Method 1',
//   Lkeys.pleaseConfigureSubscription:
//       'Make sure you configure Purchases before trying to get the default instance. More info here',
// };
